language: java
jdk:
  - oraclejdk8
sudo: false
services:
  - redis-server
addons:
  apt:
    packages:
      - oracle-java8-installer
install: true
script:
  - mvn clean compile package install -Dmaven.javadoc.skip=true -B -V
