dist: trusty
language: java
jdk:
  - oraclejdk8
sudo: false
services:
  - redis-server
addons:
  apt:
    packages:
      - oracle-java8-installer
install: true
script:
  - rm -rf karate-grpc-helper/helper
  - mvn clean compile package install -Dmaven.javadoc.skip=true -Dmaven.test.skip=true -B -V
  - cd karate-grpc-helper
  - mvn exec:java -Dexec.mainClass=com.github.thinkerou.karate.helper.Main
  - cd ..
  - mvn test
